import { ItemCarrinho, Produto } from "../types/domain";
import { productAssets } from "./assets";

export const mockProducts: Produto[] = [
  {
    id_produto: 1001,
    nome: "Scarpin Fatal Lady A1025304360002",
    nome_categoria: "Salto Alto",
    categoria: { id: 3, nome: "Salto Alto", slug: "salto-alto" },
    preco: 299.9,
    estoque: 12,
    tamanhos: "34/35/36/37/38/39",
    tamanhos_disponiveis: [34, 35, 36, 37, 38, 39],
    caminhoimagem: productAssets.scarpinRed,
    cor: "Vermelho",
    descricao:
      "Conforto e estilo se encontram neste design exclusivo. Confeccionado com materiais de alta qualidade, este produto oferece durabilidade e elegância para qualquer ocasião.",
    nota_media: 4.8,
  },
  {
    id_produto: 1002,
    nome: "Scarpin Fatal Lady A1088400010045",
    nome_categoria: "Salto Alto",
    categoria: { id: 3, nome: "Salto Alto", slug: "salto-alto" },
    preco: 329.9,
    estoque: 8,
    tamanhos: "35/36/37/38/39",
    tamanhos_disponiveis: [35, 36, 37, 38, 39],
    caminhoimagem: productAssets.scarpinBlack,
    cor: "Preto",
    descricao:
      "Acabamento premium e presença marcante para produções elegantes no dia a dia ou em ocasiões especiais.",
    nota_media: 4.7,
  },
  {
    id_produto: 2001,
    nome: "Bota Fatal Lady 0216687840012U",
    nome_categoria: "Botas",
    categoria: { id: 2, nome: "Botas", slug: "botas" },
    preco: 389.9,
    estoque: 6,
    tamanhos: "35/36/37/38/39/40",
    tamanhos_disponiveis: [35, 36, 37, 38, 39, 40],
    caminhoimagem: productAssets.bota1,
    cor: "Preto",
    descricao:
      "Modelo robusto e sofisticado, pensado para unir presença visual, estabilidade e conforto.",
    nota_media: 4.9,
  },
  {
    id_produto: 2002,
    nome: "Bota Fatal Lady 1275401560001U",
    nome_categoria: "Botas",
    categoria: { id: 2, nome: "Botas", slug: "botas" },
    preco: 419.9,
    estoque: 5,
    tamanhos: "34/35/36/37/38",
    tamanhos_disponiveis: [34, 35, 36, 37, 38],
    caminhoimagem: productAssets.bota2,
    cor: "Marrom",
    descricao:
      "Silhueta moderna com acabamento premium, ideal para produções de inverno com identidade Fatal Lady.",
    nota_media: 4.6,
  },
  {
    id_produto: 3001,
    nome: "Rasteirinha Fatal Lady A0201205600002",
    nome_categoria: "Rasteirinha",
    categoria: { id: 4, nome: "Rasteirinha", slug: "rasteirinha" },
    preco: 159.9,
    estoque: 18,
    tamanhos: "34/35/36/37/38/39",
    tamanhos_disponiveis: [34, 35, 36, 37, 38, 39],
    caminhoimagem: productAssets.rasteira1,
    cor: "Nude",
    descricao:
      "Leve, versátil e confortável para acompanhar a rotina com um acabamento delicado.",
    nota_media: 4.5,
  },
  {
    id_produto: 3002,
    nome: "Rasteirinha Fatal Lady A0448505300001",
    nome_categoria: "Rasteirinha",
    categoria: { id: 4, nome: "Rasteirinha", slug: "rasteirinha" },
    preco: 179.9,
    estoque: 16,
    tamanhos: "34/35/36/37/38/39/40",
    tamanhos_disponiveis: [34, 35, 36, 37, 38, 39, 40],
    caminhoimagem: productAssets.rasteira2,
    cor: "Dourado",
    descricao:
      "Acabamento elegante com perfil baixo e visual refinado para dias mais leves.",
    nota_media: 4.4,
  },
  {
    id_produto: 4001,
    nome: "Tênis Fatal Lady A1212400260003",
    nome_categoria: "Tênis",
    categoria: { id: 6, nome: "Tênis", slug: "tenis" },
    preco: 259.9,
    estoque: 20,
    tamanhos: "35/36/37/38/39/40",
    tamanhos_disponiveis: [35, 36, 37, 38, 39, 40],
    caminhoimagem: productAssets.tenis1,
    cor: "Branco",
    descricao:
      "Design moderno e confortável para acompanhar a rotina com estilo e mobilidade.",
    nota_media: 4.6,
  },
  {
    id_produto: 4002,
    nome: "Tênis Fatal Lady A1347600080011",
    nome_categoria: "Tênis",
    categoria: { id: 6, nome: "Tênis", slug: "tenis" },
    preco: 279.9,
    estoque: 14,
    tamanhos: "34/35/36/37/38/39",
    tamanhos_disponiveis: [34, 35, 36, 37, 38, 39],
    caminhoimagem: productAssets.tenis2,
    cor: "Off-white",
    descricao:
      "Construção casual premium com acabamento esportivo alinhado à estética da marca.",
    nota_media: 4.7,
  },
  {
    id_produto: 5001,
    nome: "Sapatilha Fatal Lady A1190600970053",
    nome_categoria: "Sapatilha",
    categoria: { id: 5, nome: "Sapatilha", slug: "sapatilha" },
    preco: 189.9,
    estoque: 15,
    tamanhos: "34/35/36/37/38",
    tamanhos_disponiveis: [34, 35, 36, 37, 38],
    caminhoimagem: productAssets.sapatilha1,
    cor: "Bege",
    descricao:
      "Sapatilha leve com leitura feminina e elegante para uso prolongado com conforto.",
    nota_media: 4.3,
  },
  {
    id_produto: 6001,
    nome: "Sandália Fatal Lady A1017611420001",
    nome_categoria: "Sandália",
    categoria: { id: 1, nome: "Sandália", slug: "sandalia" },
    preco: 219.9,
    estoque: 10,
    tamanhos: "34/35/36/37/38/39",
    tamanhos_disponiveis: [34, 35, 36, 37, 38, 39],
    caminhoimagem: productAssets.sandalia1,
    cor: "Preto",
    descricao:
      "Sandália elegante com presença visual marcante e construção pensada para eventos e ocasiões especiais.",
    nota_media: 4.8,
  },
];

export const featuredProducts = mockProducts.slice(0, 4);

export const initialCartItems: ItemCarrinho[] = [
  {
    id: "cart-1001-37",
    produto_id: 1001,
    produto: mockProducts[0],
    quantidade: 1,
    preco_unitario: mockProducts[0].preco,
    tamanho: 37,
  },
  {
    id: "cart-4001-38",
    produto_id: 4001,
    produto: mockProducts[6],
    quantidade: 1,
    preco_unitario: mockProducts[6].preco,
    tamanho: 38,
  },
];
